# Project 1
# Kubernetes manifest file, authored by Tobechukwu Emeruem
# Complete Manifest Where in single yml we defined Deployment & Service for Project1 & Persistent Volume Claim (with default  StorageClass), ReplicaSet & Service For Mongo.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: project1deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: project1image
  template:
    metadata:
      name: project1pod
      labels:
        app: project1image
    spec:
      containers:
      - name: project1container
        image: Tobechukwu/spring-boot-mongo
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_DB_USERNAME
          value: devdb
        - name: MONGO_DB_PASSWORD
          value: devdb@123
        - name: MONGO_DB_HOSTNAME
          value: mongo 
---
#LB
apiVersion: v1
kind: Service
metadata:
  name: project1LB
spec:
  selector:
    app: project1app
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer
---
#PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodbpvc 
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
#RS
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mongodbrs
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
     metadata:
       name: mongodbpod
       labels:
         app: mongodb
     spec:
       volumes:
       - name: pvc
         persistentVolumeClaim:
           claimName: mongodbpvc     
       containers:
       - name: mongodbcontainer
         image: mongo
         ports:
         - containerPort: 27017
         env:
         - name: MONGO_INITDB_ROOT_USERNAME
           value: devdb
         - name: MONGO_INITDB_ROOT_PASSWORD
           value: devdb@123
         volumeMounts:
         - name: pvc
           mountPath: /data/db   
---
#ClusterIP
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017
